import { InterpretedWorkout, SetInterval } from '../models/WorkoutTypes';
import { formatSecondsAsTime } from '../dsl/parseTime';

export type PdfViewMode = 'coach' | 'swimmer';

/**
 * Render an interpreted workout as an HTML document string.
 *
 * For v1:
 *  - Simple, readable layout
 *  - Slightly different text for coach vs swimmer views
 *  - Inline CSS for easy server-side rendering
 */
export function renderWorkoutHtml(
  workout: InterpretedWorkout,
  view: PdfViewMode
): string {
  const title = workout.header.title || 'SwimSet Workout';
  const pool = workout.header.poolLengthMeters
    ? `${workout.header.poolLengthMeters}m pool`
    : 'Pool length: N/A';

  const totalDistance = workout.totals.totalDistanceMeters ?? 0;
  const focus = workout.header.focus || 'Unspecified focus';
  const profile = workout.header.profile || 'Unspecified profile';

  const estimated = workout.totals.estimatedMinutes
    ? `${workout.totals.estimatedMinutes.toFixed(1)} min`
    : 'N/A';

  const sections = groupSetsBySection(workout.sets);

  const sectionsHtml = Object.entries(sections)
    .map(([sectionName, sets]) => renderSection(sectionName, sets, workout, view))
    .join('\n');

  const warningsHtml =
    workout.warnings.length > 0
      ? `
      <div class="warnings">
        <h3>Warnings</h3>
        <ul>
          ${workout.warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join('\n')}
        </ul>
      </div>
    `
      : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    * {
      box-sizing: border-box;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
      margin: 0;
      padding: 24px;
      color: #111827;
      background-color: #ffffff;
      font-size: 14px;
      line-height: 1.4;
    }

    .page {
      max-width: 800px;
      margin: 0 auto;
    }

    h1 {
      font-size: 28px;
      margin-bottom: 4px;
    }

    .meta {
      margin-bottom: 16px;
      font-size: 13px;
      color: #4b5563;
    }

    .meta span {
      margin-right: 12px;
    }

    .view-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      font-weight: 600;
      background-color: ${view === 'coach' ? '#fee2e2' : '#d1fae5'};
      color: ${view === 'coach' ? '#b91c1c' : '#065f46'};
    }

    .section {
      margin-bottom: 16px;
      padding: 12px 12px 8px;
      border-radius: 8px;
      border: 1px solid #e5e7eb;
      background-color: #f9fafb;
    }

    .section-title {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      margin-bottom: 8px;
    }

    .section-title h2 {
      font-size: 16px;
      margin: 0;
      text-transform: capitalize;
    }

    .section-distance {
      font-size: 12px;
      color: #6b7280;
    }

    table.sets-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }

    table.sets-table th,
    table.sets-table td {
      padding: 4px 6px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }

    table.sets-table th {
      font-weight: 600;
      color: #4b5563;
      background-color: #f3f4f6;
    }

    table.sets-table tr:last-child td {
      border-bottom: none;
    }

    .warnings {
      margin-top: 16px;
      padding: 10px 12px;
      border-radius: 8px;
      background-color: #fffbeb;
      border: 1px solid #fbbf24;
      font-size: 13px;
    }

    .warnings h3 {
      margin: 0 0 4px;
      font-size: 14px;
      color: #b45309;
    }

    .footer {
      margin-top: 24px;
      font-size: 11px;
      color: #9ca3af;
      text-align: right;
    }
  </style>
</head>
<body>
  <div class="page">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">
      <span>${escapeHtml(pool)}</span>
      <span>Total: ${totalDistance} m</span>
      <span>Focus: ${escapeHtml(focus)}</span>
      <span>Profile: ${escapeHtml(profile)}</span>
      <span>Est: ${escapeHtml(estimated)}</span>
      <span class="view-badge">${view === 'coach' ? 'Coach view' : 'Swimmer view'}</span>
    </div>

    ${sectionsHtml}

    ${warningsHtml}

    <div class="footer">
      Generated by SwimSet
    </div>
  </div>
</body>
</html>`;
}

function groupSetsBySection(sets: SetInterval[]): Record<string, SetInterval[]> {
  const sections: Record<string, SetInterval[]> = {};
  for (const set of sets) {
    if (!sections[set.section]) {
      sections[set.section] = [];
    }
    sections[set.section].push(set);
  }
  return sections;
}

function renderSection(
  sectionName: string,
  sets: SetInterval[],
  workout: InterpretedWorkout,
  view: PdfViewMode
): string {
  const sectionDistance = workout.totals.distanceBySection[sectionName] ?? 0;

  const headerHtml = `
    <div class="section-title">
      <h2>${escapeHtml(sectionName)}</h2>
      <span class="section-distance">${sectionDistance} m</span>
    </div>
  `;

  const rowsHtml = sets
    .map((set) => renderSetRow(set, view))
    .join('\n');

  const tableHeaders =
    view === 'coach'
      ? `
        <tr>
          <th>Set</th>
          <th>Stroke</th>
          <th>Send-off</th>
          <th>Intensity</th>
        </tr>
      `
      : `
        <tr>
          <th>Set</th>
          <th>Stroke</th>
          <th>Rest / Interval</th>
        </tr>
      `;

  return `
    <div class="section">
      ${headerHtml}
      <table class="sets-table">
        <thead>
          ${tableHeaders}
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>
    </div>
  `;
}

function renderSetRow(set: SetInterval, view: PdfViewMode): string {
  const baseLabel = `${set.reps} x ${set.distanceMeters} m`;
  const intensity = set.intensity ?? '';
  const sendOff = set.sendOffSeconds ? formatSecondsAsTime(set.sendOffSeconds) : '';

  if (view === 'coach') {
    return `
      <tr>
        <td>${escapeHtml(baseLabel)}</td>
        <td>${escapeHtml(set.stroke)}</td>
        <td>${escapeHtml(sendOff ?? '')}</td>
        <td>${escapeHtml(intensity)}</td>
      </tr>
    `;
  }

  // swimmer view
  return `
    <tr>
      <td>${escapeHtml(baseLabel)}</td>
      <td>${escapeHtml(set.stroke)}</td>
      <td>${escapeHtml(sendOff ?? '')}</td>
    </tr>
  `;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}